// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: proto/ChittyChat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequestCtS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                             // message
	UserName    string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`                           // the clients name
	LamportTime int64  `protobuf:"varint,3,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"` // get the local time
}

func (x *MessageRequestCtS) Reset() {
	*x = MessageRequestCtS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ChittyChat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequestCtS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequestCtS) ProtoMessage() {}

func (x *MessageRequestCtS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ChittyChat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequestCtS.ProtoReflect.Descriptor instead.
func (*MessageRequestCtS) Descriptor() ([]byte, []int) {
	return file_proto_ChittyChat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequestCtS) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequestCtS) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MessageRequestCtS) GetLamportTime() int64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type JoinRequestCtS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"` // when want to join then register the client name
}

func (x *JoinRequestCtS) Reset() {
	*x = JoinRequestCtS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ChittyChat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequestCtS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequestCtS) ProtoMessage() {}

func (x *JoinRequestCtS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ChittyChat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequestCtS.ProtoReflect.Descriptor instead.
func (*JoinRequestCtS) Descriptor() ([]byte, []int) {
	return file_proto_ChittyChat_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequestCtS) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type JoinResponseStC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinMsg     string `protobuf:"bytes,1,opt,name=joinMsg,proto3" json:"joinMsg,omitempty"`                             // message that a client has joined
	LamportTime int64  `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"` // get the localtime that the client joined
}

func (x *JoinResponseStC) Reset() {
	*x = JoinResponseStC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ChittyChat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponseStC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponseStC) ProtoMessage() {}

func (x *JoinResponseStC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ChittyChat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponseStC.ProtoReflect.Descriptor instead.
func (*JoinResponseStC) Descriptor() ([]byte, []int) {
	return file_proto_ChittyChat_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponseStC) GetJoinMsg() string {
	if x != nil {
		return x.JoinMsg
	}
	return ""
}

func (x *JoinResponseStC) GetLamportTime() int64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type Close struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Close) Reset() {
	*x = Close{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ChittyChat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ChittyChat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_proto_ChittyChat_proto_rawDescGZIP(), []int{3}
}

var File_proto_ChittyChat_proto protoreflect.FileDescriptor

var file_proto_ChittyChat_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68,
	0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79,
	0x43, 0x68, 0x61, 0x74, 0x22, 0x6c, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x74, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x74, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x4e, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a,
	0x0c, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x07, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x32, 0xae, 0x01, 0x0a, 0x11, 0x43, 0x68,
	0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x2e, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x74, 0x53,
	0x1a, 0x1d, 0x2e, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x74, 0x53, 0x12,
	0x49, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e,
	0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x74, 0x53, 0x1a, 0x1d, 0x2e, 0x43, 0x68, 0x69, 0x74,
	0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x74, 0x53, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x43, 0x68,
	0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ChittyChat_proto_rawDescOnce sync.Once
	file_proto_ChittyChat_proto_rawDescData = file_proto_ChittyChat_proto_rawDesc
)

func file_proto_ChittyChat_proto_rawDescGZIP() []byte {
	file_proto_ChittyChat_proto_rawDescOnce.Do(func() {
		file_proto_ChittyChat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ChittyChat_proto_rawDescData)
	})
	return file_proto_ChittyChat_proto_rawDescData
}

var file_proto_ChittyChat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ChittyChat_proto_goTypes = []any{
	(*MessageRequestCtS)(nil), // 0: ChittyChat.MessageRequestCtS
	(*JoinRequestCtS)(nil),    // 1: ChittyChat.JoinRequestCtS
	(*JoinResponseStC)(nil),   // 2: ChittyChat.JoinResponseStC
	(*Close)(nil),             // 3: ChittyChat.Close
}
var file_proto_ChittyChat_proto_depIdxs = []int32{
	0, // 0: ChittyChat.ChittyChatService.PublishMessage:input_type -> ChittyChat.MessageRequestCtS
	1, // 1: ChittyChat.ChittyChatService.ChatStream:input_type -> ChittyChat.JoinRequestCtS
	0, // 2: ChittyChat.ChittyChatService.PublishMessage:output_type -> ChittyChat.MessageRequestCtS
	0, // 3: ChittyChat.ChittyChatService.ChatStream:output_type -> ChittyChat.MessageRequestCtS
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ChittyChat_proto_init() }
func file_proto_ChittyChat_proto_init() {
	if File_proto_ChittyChat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ChittyChat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MessageRequestCtS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ChittyChat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRequestCtS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ChittyChat_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JoinResponseStC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ChittyChat_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Close); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ChittyChat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ChittyChat_proto_goTypes,
		DependencyIndexes: file_proto_ChittyChat_proto_depIdxs,
		MessageInfos:      file_proto_ChittyChat_proto_msgTypes,
	}.Build()
	File_proto_ChittyChat_proto = out.File
	file_proto_ChittyChat_proto_rawDesc = nil
	file_proto_ChittyChat_proto_goTypes = nil
	file_proto_ChittyChat_proto_depIdxs = nil
}
